In [1]:
import pandas as pd

In [2]:
house_data = pd.read_csv("data/merged_original_data.csv")
print("inhouse_data.shape: ", house_data.shape)
genes_list = list(house_data['Gene'])

processed_data = pd.read_csv("data/ready2analyze.csv")
print("processed_data.shape: ", processed_data.shape)

inhouse_data.shape:  (20812, 136)
processed_data.shape:  (422, 16383)

In [3]:
processed_data.head(5)

,outcomes,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,...,RP11-344P13.1,YBX1P1,RP4-758J18.2,AC083949.1,C17orf89,AC068279.3,RP5-1142A6.2,POT1-AS1,LINC00863,RP11-441O15.3
0,1,-0.697033,1.512795,0.458046,-2.302145,-1.531716,1.852312,1.635732,0.418809,0.444892,...,-0.667051,1.551203,0.504736,-0.451459,-0.552554,-0.758975,0.857814,1.613504,-0.659650,-0.261329
1,1,-0.458046,0.464653,0.545648,-1.119251,-1.409228,0.128056,2.516629,0.956415,0.164080,...,0.386600,0.249056,-1.176647,-1.512795,0.947072,0.116088,0.697033,1.086515,-0.128056,-0.766922
2,1,0.498001,-0.008910,-1.141758,-1.075859,-0.182169,-0.230716,0.601671,-1.024314,1.225521,...,0.212453,-0.242934,-0.901545,-1.024314,-0.438343,-0.594567,1.362672,0.984958,-0.342164,-0.919527
3,1,0.074317,-0.279813,-0.255188,0.928631,1.119251,-0.200318,1.409228,-0.348469,-0.152051,...,-1.304852,0.418809,-0.956415,-0.975356,1.318896,-0.298394,1.377860,0.292189,1.034403,-0.279813
4,1,-1.476497,-1.433697,-0.128056,-1.318896,1.277511,0.348469,1.494400,-0.170103,-0.380207,...,-0.329595,0.329595,0.236820,-0.615969,0.261329,-0.751076,1.852312,1.459056,0.242934,0.026733

In [5]:

processed_genes = processed_data.columns.tolist()
processed_genes

processed_genes.remove('outcomes')

processed_genes

to_remove = []
for i in range(len(processed_genes)):
    if processed_genes[i] in genes_list:
        #print("gene existsed: ", processed_genes[i])
        pass
    else:
        print("gene not existed: ", processed_genes[i])
        to_remove.append(processed_genes[i])
        
processed_data.head(5)

gene not existed:  ENSG00000002586.1
gene not existed:  AOC1
gene not existed:  AC004381.6
gene not existed:  KMT2E
gene not existed:  KDM7A
gene not existed:  RGPD5
gene not existed:  PRDM11
gene not existed:  RTEL1-TNFRSF6B
gene not existed:  JADE2
gene not existed:  UTS2
gene not existed:  MCUR1
gene not existed:  KMT2C
gene not existed:  NDC1
gene not existed:  YBX3
gene not existed:  ZNF112
gene not existed:  DMRT3
gene not existed:  MEF2BNB-MEF2B
gene not existed:  STON1-GTF2A1L
gene not existed:  TMEM260
gene not existed:  MRPS34
gene not existed:  JADE1
gene not existed:  BRINP1
gene not existed:  SENP1
gene not existed:  CRYBG3
gene not existed:  KLHL42
gene not existed:  LZTS3
gene not existed:  SLC8B1
gene not existed:  CDIP1
gene not existed:  MLTK
gene not existed:  AGO1
gene not existed:  XXbac-B461K10.4
gene not existed:  IGFALS
gene not existed:  2-Mar
gene not existed:  MISP
gene not existed:  CEP170B
gene not existed:  3-Sep
gene not existed:  RTCB
gene not existed:  MIEF1
gene not existed:  VCPKMT
gene not existed:  CNIH1
gene not existed:  GALNT16
gene not existed:  UQCC1
gene not existed:  NELFCD
gene not existed:  MTG2
gene not existed:  CCM2L
gene not existed:  TLDC2
gene not existed:  MROH8
gene not existed:  PCSK1N
gene not existed:  JADE3
gene not existed:  PBDC1
gene not existed:  SUPT20H
gene not existed:  IRG1
gene not existed:  TANGO6
gene not existed:  CAPN15
gene not existed:  CORO7-PAM16
gene not existed:  KNOP1
gene not existed:  ZNF106
gene not existed:  CCDC61
gene not existed:  TJP3
gene not existed:  DKFZP761J1410
gene not existed:  STAG3L4
gene not existed:  ABHD17B
gene not existed:  CCSER2
gene not existed:  EDRF1
gene not existed:  NEURL1
gene not existed:  4-Sep
gene not existed:  SC5D
gene not existed:  GALNT18
gene not existed:  C2CD5
gene not existed:  RP11-22B23.1
gene not existed:  SMIM8
gene not existed:  GLTSCR1L
gene not existed:  DNPH1
gene not existed:  TRAPPC13
gene not existed:  EFCC1
gene not existed:  ABHD14A-ACY1
gene not existed:  GPR75-ASB3
gene not existed:  EVA1A
gene not existed:  RMDN2
gene not existed:  RP11-268J15.5
gene not existed:  MYCL
gene not existed:  PINK1-AS
gene not existed:  CCDC181
gene not existed:  MROH9
gene not existed:  MTFR1L
gene not existed:  2-Mar.1
gene not existed:  KMT2A
gene not existed:  FAM47E-STBD1
gene not existed:  TRIM32
gene not existed:  AREL1
gene not existed:  SPATA1
gene not existed:  7-Sep
gene not existed:  NT5C3A
gene not existed:  RAB9B
gene not existed:  AGO2
gene not existed:  DAW1
gene not existed:  TMEM189-UBE2V1
gene not existed:  ENSG00000124333.1
gene not existed:  ENSG00000124334.1
gene not existed:  OARD1
gene not existed:  MYRF
gene not existed:  SSUH2
gene not existed:  6-Sep
gene not existed:  TMEM255A
gene not existed:  CD70
gene not existed:  MGME1
gene not existed:  MMP24-AS1
gene not existed:  AGO3
gene not existed:  FLRT1
gene not existed:  HTN1
gene not existed:  CTAG2
gene not existed:  TICAM1
gene not existed:  TBC1D27
gene not existed:  STRIP2
gene not existed:  MRPS12
gene not existed:  KNSTRN
gene not existed:  ACKR4
gene not existed:  ABHD17A
gene not existed:  ERMARD
gene not existed:  THEM6
gene not existed:  COLGALT1
gene not existed:  RBBP8NL
gene not existed:  TXLNG2P
gene not existed:  PRR7
gene not existed:  GALNT15
gene not existed:  MGAT1
gene not existed:  RP11-798G7.5
gene not existed:  CLUHP3
gene not existed:  KRT17P1
gene not existed:  LRRC9
gene not existed:  SLX1A
gene not existed:  TIMM10B
gene not existed:  CLUH
gene not existed:  ANKEF1
gene not existed:  OSER1
gene not existed:  HMGB1P5
gene not existed:  GPALPP1
gene not existed:  GGT2
gene not existed:  TMEM254
gene not existed:  DPH6
gene not existed:  AGO4
gene not existed:  TMEM258
gene not existed:  C5AR2
gene not existed:  C9orf40
gene not existed:  CTSL
gene not existed:  TMEM243
gene not existed:  KRT121P
gene not existed:  RPL13AP25
gene not existed:  CHST12
gene not existed:  ABHD17C
gene not existed:  7-Mar
gene not existed:  CTSV
gene not existed:  TMEM261
gene not existed:  ZSCAN9
gene not existed:  CMTR1
gene not existed:  UQCC2
gene not existed:  RMDN3
gene not existed:  RPL7P9
gene not existed:  SIX3
gene not existed:  CARF
gene not existed:  11-Sep
gene not existed:  GUCD1
gene not existed:  9-Mar
gene not existed:  RITA1
gene not existed:  TTC6
gene not existed:  MAP1LC3B
gene not existed:  TLDC1
gene not existed:  ZSCAN32
gene not existed:  TOB1
gene not existed:  GAREM
gene not existed:  WDR45B
gene not existed:  NT5C3B
gene not existed:  hsa-mir-1199
gene not existed:  MVB12A
gene not existed:  ERVK3-1
gene not existed:  C19orf52
gene not existed:  C1orf222
gene not existed:  C1orf216
gene not existed:  EVA1B
gene not existed:  STRIP1
gene not existed:  XCL1
gene not existed:  AC027612.6
gene not existed:  MLK4
gene not existed:  HNRNPLL
gene not existed:  TMEM177
gene not existed:  NT5DC4
gene not existed:  ACKR3
gene not existed:  4-Mar
gene not existed:  POMGNT2
gene not existed:  ACKR2
gene not existed:  RP11-977G19.10
gene not existed:  CENPC
gene not existed:  1-Mar
gene not existed:  6-Mar
gene not existed:  PRIM2
gene not existed:  TPBG
gene not existed:  PNRC1
gene not existed:  TBC1D32
gene not existed:  MTFR2
gene not existed:  C6orf211
gene not existed:  AC006014.8
gene not existed:  C7orf55-LUC7L2
gene not existed:  KRBOX4
gene not existed:  FRMPD3
gene not existed:  HMCN2
gene not existed:  DPH7
gene not existed:  PROSER2
gene not existed:  ADIRF
gene not existed:  SLX4IP
gene not existed:  CNBD2
gene not existed:  FRMPD2P2
gene not existed:  CTF1
gene not existed:  UBC
gene not existed:  CENPU
gene not existed:  AC093838.4
gene not existed:  GPATCH11
gene not existed:  HSPB8
gene not existed:  NADK2
gene not existed:  HNRNPDL
gene not existed:  UBALD1
gene not existed:  FAM27C
gene not existed:  14-Sep
gene not existed:  AK9
gene not existed:  TRIM74
gene not existed:  NIFK
gene not existed:  MICU3
gene not existed:  MAP3K7CL
gene not existed:  KCNS2
gene not existed:  IGKV1OR-2
gene not existed:  TBC1D31
gene not existed:  B3GNT7
gene not existed:  RP11-66N24.4
gene not existed:  PALM2-AKAP2
gene not existed:  GAREML
gene not existed:  DRC1
gene not existed:  ANKRD61
gene not existed:  CNOT11
gene not existed:  DMTN
gene not existed:  CCAR2
gene not existed:  PAXBP1
gene not existed:  CLDN14
gene not existed:  PTMS
gene not existed:  M1AP
gene not existed:  EFCAB14
gene not existed:  ANKRD18CP
gene not existed:  FAM115D
gene not existed:  ZNF66
gene not existed:  SPATC1L
gene not existed:  C19orf47
gene not existed:  ZBTB7B
gene not existed:  COL26A1
gene not existed:  AC008132.13
gene not existed:  RNASEK-C17orf49
gene not existed:  MSLNL
gene not existed:  CYB561A3
gene not existed:  COA7
gene not existed:  BRINP3
gene not existed:  NBPF8
gene not existed:  C1orf145
gene not existed:  PCDP1
gene not existed:  LINC01116
gene not existed:  SMIM14
gene not existed:  SMIM12
gene not existed:  EXO5
gene not existed:  PRIMPOL
gene not existed:  8-Sep
gene not existed:  INTS4L1
gene not existed:  SPIDR
gene not existed:  GPER1
gene not existed:  PDP1
gene not existed:  RPP25L
gene not existed:  NFIL3
gene not existed:  RP11-213G2.3
gene not existed:  8-Mar
gene not existed:  GJB2
gene not existed:  MICU2
gene not existed:  AMER2
gene not existed:  KBTBD6
gene not existed:  NSMF
gene not existed:  FAM35BP
gene not existed:  SMCO4
gene not existed:  hsa-mir-7162
gene not existed:  MYRFL
gene not existed:  PLEKHF1
gene not existed:  TVP23A
gene not existed:  ZNF667-AS1
gene not existed:  MESP1
gene not existed:  ZBTB39
gene not existed:  MS4A8
gene not existed:  EVA1C
gene not existed:  NKX3-1
gene not existed:  DUS2
gene not existed:  ENSG00000167393.1
gene not existed:  SPATA33
gene not existed:  KMT2D
gene not existed:  CTD-2369P2.10
gene not existed:  RP11-25K19.1
gene not existed:  2-Sep
gene not existed:  ENSG00000168939.1
gene not existed:  JMJD7-PLA2G4B
gene not existed:  ENSG00000169084.1
gene not existed:  ENSG00000169093.1
gene not existed:  ENSG00000169100.1
gene not existed:  RP11-231C14.4
gene not existed:  NPIPB3
gene not existed:  GPRIN1
gene not existed:  LINGO1
gene not existed:  MUC3A
gene not existed:  TIGD4
gene not existed:  FAM153A
gene not existed:  SIMC1
gene not existed:  RP11-423H2.1
gene not existed:  AC018720.10
gene not existed:  RP11-262H14.4
gene not existed:  CR848007.2
gene not existed:  FAXDC2
gene not existed:  LRRN2
gene not existed:  AC005280.1
gene not existed:  RASA4B
gene not existed:  SOCS6
gene not existed:  AC093323.3
gene not existed:  PAQR8
gene not existed:  NCBP2L
gene not existed:  SIGLEC17P
gene not existed:  HSFX1
gene not existed:  FUT3
gene not existed:  C9orf16
gene not existed:  SCAND1
gene not existed:  TMEM37
gene not existed:  ZBTB26
gene not existed:  RP11-443P15.2
gene not existed:  TVP23B
gene not existed:  FBXW10
gene not existed:  SRGAP2C
gene not existed:  TPSAB1
gene not existed:  COPRS
gene not existed:  IL17D
gene not existed:  MIR4435-1HG
gene not existed:  1-Dec
gene not existed:  ZBTB21
gene not existed:  TRAPPC3L
gene not existed:  SPDYE2B
gene not existed:  AP000769.1
gene not existed:  CCDC13-AS1
gene not existed:  10-Mar
gene not existed:  3-Mar
gene not existed:  LRRC63
gene not existed:  NRROS
gene not existed:  FAM3C2
gene not existed:  RP11-23P13.6
gene not existed:  STAG3L3
gene not existed:  RP11-313P13.4
gene not existed:  C20orf166-AS1
gene not existed:  ANKRD36C
gene not existed:  C4orf32
gene not existed:  AMY1B
gene not existed:  CHST2
gene not existed:  FAM211A-AS1
gene not existed:  TVP23C
gene not existed:  TMEM51-AS1
gene not existed:  GOLGA8A
gene not existed:  PHYKPL
gene not existed:  C11orf68
gene not existed:  SUGCT
gene not existed:  LINC01106
gene not existed:  RP11-121M22.1
gene not existed:  RP11-544L8__B.4
gene not existed:  AL445665.1
gene not existed:  SMIM19
gene not existed:  IDSP1
gene not existed:  DIRAS1
gene not existed:  CTD-2368P22.1
gene not existed:  KBTBD11
gene not existed:  RMDN1
gene not existed:  SCAND2P
gene not existed:  CDK5R1
gene not existed:  C15orf56
gene not existed:  AL358781.1
gene not existed:  MRVI1-AS1
gene not existed:  ZBTB34
gene not existed:  LINC00982
gene not existed:  NUDT4P1
gene not existed:  NAP1L4P1
gene not existed:  RP11-551L14.1
gene not existed:  RP11-218M22.1
gene not existed:  ZFAS1
gene not existed:  MIEF2
gene not existed:  NIM1K
gene not existed:  GPR4
gene not existed:  PGBD5
gene not existed:  RP11-16K12.1
gene not existed:  AC105206.1
gene not existed:  CTD-2201E18.3
gene not existed:  AC108142.1
gene not existed:  CENPBD1
gene not existed:  GOLGA8Q
gene not existed:  FAR2P2
gene not existed:  CTXN1
gene not existed:  ENSG00000178605.1
gene not existed:  C13orf45
gene not existed:  FAM132B
gene not existed:  APOLD1
gene not existed:  ZNF852
gene not existed:  RP11-363G10.2
gene not existed:  RP11-111M22.2
gene not existed:  SMCO3
gene not existed:  TMEM151A
gene not existed:  HLA-DQB1
gene not existed:  AC073072.5
gene not existed:  ZBTB18
gene not existed:  EIF3J-AS1
gene not existed:  ZBTB42
gene not existed:  RP11-169K16.9
gene not existed:  OR7E22P
gene not existed:  PCBP1-AS1
gene not existed:  MROH1
gene not existed:  AC025335.1
gene not existed:  PHC1P1
gene not existed:  GOLGA8J
gene not existed:  ZNF771
gene not existed:  PPP1R14BP3
gene not existed:  RP11-1319K7.1
gene not existed:  ZNF48
gene not existed:  1-Sep
gene not existed:  ACTA2-AS1
gene not existed:  FAR2P1
gene not existed:  TDRP
gene not existed:  MTURN
gene not existed:  EMC3-AS1
gene not existed:  C11orf71
gene not existed:  PRR26
gene not existed:  FUT7
gene not existed:  SRP9P1
gene not existed:  RP11-290F5.2
gene not existed:  CTD-2547E10.2
gene not existed:  WDFY3-AS2
gene not existed:  PDIA3P1
gene not existed:  CMTR2
gene not existed:  LSMEM1
gene not existed:  RP11-429J17.2
gene not existed:  RP4-539M6.14
gene not existed:  HLA-V
gene not existed:  C4orf50
gene not existed:  RP4-682C21.2
gene not existed:  XXyac-YRM2039.2
gene not existed:  SLX1B
gene not existed:  GPR3
gene not existed:  CELF2-AS1
gene not existed:  RP11-381O7.3
gene not existed:  TMEM259
gene not existed:  RP11-69E11.4
gene not existed:  MRPL41
gene not existed:  ENSG00000182162.1
gene not existed:  FAM153B
gene not existed:  C22orf26
gene not existed:  SPACA6P
gene not existed:  AC079354.1
gene not existed:  ENSG00000182378.1
gene not existed:  WASH6P
gene not existed:  ENSG00000182484.1
gene not existed:  EPGN
gene not existed:  C2orf82
gene not existed:  CCNYL2
gene not existed:  LINC01006
gene not existed:  TSKU
gene not existed:  RPS17L
gene not existed:  RP11-114H20.1
gene not existed:  RP11-181G12.2
gene not existed:  RIPPLY3
gene not existed:  SMDT1
gene not existed:  WT1-AS
gene not existed:  CTD-3193O13.9
gene not existed:  PLGLB1
gene not existed:  15-Sep
gene not existed:  BOLA2
gene not existed:  NPIPA1
gene not existed:  OR7E38P
gene not existed:  RP11-958N24.1
gene not existed:  TANGO2
gene not existed:  RP11-347C12.2
gene not existed:  HMCES
gene not existed:  FAM101B
gene not existed:  ASCL2
gene not existed:  NPIPA5
gene not existed:  RBM12B
gene not existed:  UTY
gene not existed:  NPIPA7
gene not existed:  SDR42E2
gene not existed:  RP5-821D11.7
gene not existed:  RPL7AP28
gene not existed:  KCNJ12
gene not existed:  GOLGA6L4
gene not existed:  C11orf72
gene not existed:  LINC00315
gene not existed:  CCSER1
gene not existed:  MROH7
gene not existed:  AP001062.7
gene not existed:  CCR10
gene not existed:  TMEM255B
gene not existed:  SNN
gene not existed:  9-Sep
gene not existed:  OR7E14P
gene not existed:  AMER1
gene not existed:  CLDN6
gene not existed:  5-Sep
gene not existed:  LRRC26
gene not existed:  SMIM10
gene not existed:  NUTM2A
gene not existed:  TMEM121
gene not existed:  MROH2A
gene not existed:  AC004980.11
gene not existed:  NELFA
gene not existed:  AC000068.5
gene not existed:  INTS5
gene not existed:  UBALD2
gene not existed:  ENSG00000185291.1
gene not existed:  SOCS1
gene not existed:  IFNLR1
gene not existed:  C19orf68
gene not existed:  RP11-504P24.4
gene not existed:  ZBTB3
gene not existed:  RP11-645C24.2
gene not existed:  NPAP1
gene not existed:  NPIPB4
gene not existed:  POMK
gene not existed:  LINC00839
gene not existed:  AC084219.4
gene not existed:  GSAP
gene not existed:  AC013271.3
gene not existed:  KIF18B
gene not existed:  FFAR4
gene not existed:  1-Mar.1
gene not existed:  AC016757.3
gene not existed:  GOLGA8R
gene not existed:  10-Sep
gene not existed:  KTN1-AS1
gene not existed:  DTX2P1
gene not existed:  MST1L
gene not existed:  CXCR3
gene not existed:  KRT17P2
gene not existed:  TMEM262
gene not existed:  CTD-2600O9.1
gene not existed:  RP11-195F19.5
gene not existed:  RP11-723O4.6
gene not existed:  ZFP69B
gene not existed:  ZFP69
gene not existed:  TMEM256-PLSCR3
gene not existed:  OR7E25P
gene not existed:  AC002472.13
gene not existed:  OR7D2
gene not existed:  RP11-43F13.1
gene not existed:  MEIS3P2
gene not existed:  GPR89B
gene not existed:  NUTM2G
gene not existed:  NUTM2B
gene not existed:  AC002398.9
gene not existed:  AGAP4
gene not existed:  CTD-2228K2.5
gene not existed:  HYKK
gene not existed:  IGHV1OR15-9
gene not existed:  C12orf55
gene not existed:  NPIPP1
gene not existed:  GOLGA8M
gene not existed:  ZBED6CL
gene not existed:  SMIM15
gene not existed:  ADRB3
gene not existed:  SKOR1
gene not existed:  LINC00910
gene not existed:  CTD-3088G3.8
gene not existed:  UTS2B
gene not existed:  DHFRP1
gene not existed:  NELFB
gene not existed:  ANKDD1B
gene not existed:  PAX8-AS1
gene not existed:  RP11-797H7.5
gene not existed:  RP11-113D6.10
gene not existed:  SPATA41
gene not existed:  USP32P3
gene not existed:  AC079610.2
gene not existed:  COLCA1
gene not existed:  EEF1A1P5
gene not existed:  GTF2IRD2
gene not existed:  AC005154.6
gene not existed:  RP11-497H16.5
gene not existed:  ZKSCAN7
gene not existed:  NPIPB15
gene not existed:  SIAH1
gene not existed:  ANKRD20A19P
gene not existed:  HRH1
gene not existed:  AC004057.1
gene not existed:  LINC00173
gene not existed:  CXorf24
gene not existed:  SNHG17
gene not existed:  CTBP1-AS2
gene not existed:  MVB12B
gene not existed:  POTEI
gene not existed:  RP11-425I13.3
gene not existed:  NPIPB9
gene not existed:  ZSCAN25
gene not existed:  RP5-874C20.3
gene not existed:  RP11-573D15.8
gene not existed:  RP11-452G18.2
gene not existed:  BX936347.1
gene not existed:  FLJ27365
gene not existed:  KB-1592A4.15
gene not existed:  C5AR1
gene not existed:  RP11-170L3.7
gene not existed:  C5orf56
gene not existed:  PRAMENP
gene not existed:  GPX1P1
gene not existed:  AC007952.6
gene not existed:  RP4-724E16.2
gene not existed:  EME2
gene not existed:  IGKV7-3
gene not existed:  CTC-301O7.4
gene not existed:  AC122129.1
gene not existed:  CCDC180
gene not existed:  AP001597.1
gene not existed:  ENSG00000197976.1
gene not existed:  5-Mar
gene not existed:  RP11-347C12.1
gene not existed:  ZBTB14
gene not existed:  TOR4A
gene not existed:  NPIPB6
gene not existed:  ENSG00000198223.1
gene not existed:  RP11-98J23.2
gene not existed:  ZKSCAN8
gene not existed:  HOXC4
gene not existed:  RP11-544M22.1
gene not existed:  BZW1P2
gene not existed:  CTD-2173L22.4
gene not existed:  ZNF587
gene not existed:  FLVCR1-AS1
gene not existed:  HLA-DRB5
gene not existed:  PPIAP22
gene not existed:  MT-ND6
gene not existed:  SSBP3-AS1
gene not existed:  MT-CO2
gene not existed:  MT-CYB
gene not existed:  RP5-857K21.11
gene not existed:  COLGALT2
gene not existed:  MT-ND2
gene not existed:  MT-ND5
gene not existed:  BRINP2
gene not existed:  MT-CO1
gene not existed:  ZNF358
gene not existed:  MT-ND3
gene not existed:  HSD3BP5
gene not existed:  MT-ND4
gene not existed:  MT-ND1
gene not existed:  CIPC
gene not existed:  MT-ATP6
gene not existed:  MT-CO3
gene not existed:  MIR429
gene not existed:  MIRLET7D
gene not existed:  MIR126
gene not existed:  RNA5S12
gene not existed:  Y_RNA
gene not existed:  RNA5S11
gene not existed:  RNA5S3
gene not existed:  RNA5S1
gene not existed:  RNA5S5
gene not existed:  SNORD104
gene not existed:  Y_RNA.1
gene not existed:  RNA5S10
gene not existed:  SNORA73B
gene not existed:  RNA5S8
gene not existed:  RNA5S17
gene not existed:  RNA5S4
gene not existed:  RNA5S6
gene not existed:  RNU4-1
gene not existed:  RN7SKP36
gene not existed:  SNORD14E
gene not existed:  RNA5S9
gene not existed:  RNA5S14
gene not existed:  RNA5S2
gene not existed:  RNA5S15
gene not existed:  RN7SK
gene not existed:  RNA5S16
gene not existed:  RNA5S7
gene not existed:  RNA5S13
gene not existed:  RNU4-2
gene not existed:  RP11-296A18.3
gene not existed:  AC105020.1
gene not existed:  AC004988.1
gene not existed:  PDCD4-AS1
gene not existed:  FAM83H-AS1
gene not existed:  RP11-176H8.1
gene not existed:  RP11-542B15.1
gene not existed:  GP1BB
gene not existed:  AC144450.2
gene not existed:  AC083799.1
gene not existed:  C1orf132
gene not existed:  RP11-296O14.3
gene not existed:  FAM229B
gene not existed:  ADAMTSL4-AS1
gene not existed:  HIST2H3C
gene not existed:  HIST2H2AA4
gene not existed:  HIST2H3A
gene not existed:  RP11-451M19.3
gene not existed:  LINC00632
gene not existed:  RP11-290F20.1
gene not existed:  LINC00963
gene not existed:  FOXO6
gene not existed:  RP4-545K15.3
gene not existed:  TIMM23B
gene not existed:  AGAP10
gene not existed:  NPY4R
gene not existed:  RP11-713P17.3
gene not existed:  TAPSAR1
gene not existed:  RP11-622K12.1
gene not existed:  RP11-219G17.4
gene not existed:  TNRC6C-AS1
gene not existed:  ERICH2
gene not existed:  DXO
gene not existed:  NELFE
gene not existed:  RP11-380J14.1
gene not existed:  ZBTB12
gene not existed:  XAGE1A
gene not existed:  AC005042.4
gene not existed:  XAGE1B
gene not existed:  XXbac-BPG32J3.20
gene not existed:  CTD-2514C3.1
gene not existed:  AC096670.3
gene not existed:  RP11-304F15.3
gene not existed:  LINC01123
gene not existed:  AC115618.1
gene not existed:  ZNRD1-AS1
gene not existed:  CTD-2126E3.1
gene not existed:  IGKV1OR2-3

,outcomes,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,...,RP11-344P13.1,YBX1P1,RP4-758J18.2,AC083949.1,C17orf89,AC068279.3,RP5-1142A6.2,POT1-AS1,LINC00863,RP11-441O15.3
0,1,-0.697033,1.512795,0.458046,-2.302145,-1.531716,1.852312,1.635732,0.418809,0.444892,...,-0.667051,1.551203,0.504736,-0.451459,-0.552554,-0.758975,0.857814,1.613504,-0.659650,-0.261329
1,1,-0.458046,0.464653,0.545648,-1.119251,-1.409228,0.128056,2.516629,0.956415,0.164080,...,0.386600,0.249056,-1.176647,-1.512795,0.947072,0.116088,0.697033,1.086515,-0.128056,-0.766922
2,1,0.498001,-0.008910,-1.141758,-1.075859,-0.182169,-0.230716,0.601671,-1.024314,1.225521,...,0.212453,-0.242934,-0.901545,-1.024314,-0.438343,-0.594567,1.362672,0.984958,-0.342164,-0.919527
3,1,0.074317,-0.279813,-0.255188,0.928631,1.119251,-0.200318,1.409228,-0.348469,-0.152051,...,-1.304852,0.418809,-0.956415,-0.975356,1.318896,-0.298394,1.377860,0.292189,1.034403,-0.279813
4,1,-1.476497,-1.433697,-0.128056,-1.318896,1.277511,0.348469,1.494400,-0.170103,-0.380207,...,-0.329595,0.329595,0.236820,-0.615969,0.261329,-0.751076,1.852312,1.459056,0.242934,0.026733

In [6]:
in_house_temp= processed_data.drop(to_remove, axis=1)

In [7]:
in_house = in_house_temp
in_house.head()

,outcomes,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,...,C4B,ADM5,ATXN1L,TMLHE-AS1,HLA-DPB2,RASAL2-AS1,ZNF812,PCOLCE-AS1,TEX26-AS1,C17orf89
0,1,-0.697033,1.512795,0.458046,-2.302145,-1.531716,1.852312,1.635732,0.418809,0.444892,...,-1.075859,-0.386600,-0.498001,0.504736,-0.735417,1.108207,1.852312,1.097296,-1.393373,-0.552554
1,1,-0.458046,0.464653,0.545648,-1.119251,-1.409228,0.128056,2.516629,0.956415,0.164080,...,-0.875105,-0.766922,-0.206382,-0.146045,-1.613504,0.984958,1.425446,0.965842,-2.159574,0.947072
2,1,0.498001,-0.008910,-1.141758,-1.075859,-0.182169,-0.230716,0.601671,-1.024314,1.225521,...,1.164860,1.318896,0.594567,-0.743224,0.393009,1.238206,-0.323330,1.377860,-0.182169,-0.438343
3,1,0.074317,-0.279813,-0.255188,0.928631,1.119251,-0.200318,1.409228,-0.348469,-0.152051,...,0.170103,0.498001,0.348469,0.823977,0.994653,0.994653,-0.279813,1.086515,-0.026733,1.318896
4,1,-1.476497,-1.433697,-0.128056,-1.318896,1.277511,0.348469,1.494400,-0.170103,-0.380207,...,-0.471280,0.026733,-1.124824,1.318896,-1.409228,1.004441,2.516629,0.531912,-2.102094,0.261329

In [8]:
in_house.to_csv("data/processed_inhouse.csv", index=False)

In [9]:
#data_combined.to_csv("processed_data/rfs15_amirSel.csv", index=False)

In [10]:
in_house.shape

(422, 15143)

In [11]:
df_dropped = in_house.dropna(axis=1)

In [12]:
df_dropped.shape

(422, 15143)

In [13]:
df_dropped.to_csv("data/processed-inhouse.csv", index=False)

In [19]:
df_dropped.head(5)

,Outcomes,A1BG,A1CF,A2M,A2ML1,A2MP1,A4GALT,A4GNT,AAAS,AACS,...,GGT7,GGT8P,GGTA1P,GGTLC1,GGTLC2,GH1,GH2,GHDC,GHITM,GHR
0,1,5.615586,0.0,6.827090,5.225640,3.689587,5.891221,0.0,7.793923,9.552534,...,7.401082,0.0,0.0,0.0,0.0,0.0,0.0,5.922248,3.537584,0.000000
1,1,7.337469,0.0,5.587447,0.000000,0.000000,0.000000,0.0,6.985997,7.909375,...,6.985997,0.0,0.0,0.0,0.0,0.0,0.0,5.449944,0.000000,0.000000
2,1,3.867909,0.0,7.393978,2.924493,3.224053,3.031408,0.0,5.838763,7.739753,...,5.951973,0.0,0.0,0.0,0.0,0.0,0.0,3.224053,6.094418,0.000000
3,1,1.772974,0.0,5.473414,2.772974,4.188012,0.000000,0.0,6.787924,7.695806,...,7.306953,0.0,0.0,0.0,0.0,0.0,0.0,3.647443,5.232406,0.000000
4,1,5.634852,0.0,6.300433,2.361833,3.098799,5.477311,0.0,6.268724,8.683762,...,7.219814,0.0,0.0,0.0,0.0,0.0,0.0,3.776871,2.776871,3.776871

In [ ]:
############################################################################################################################

In [3]:
import pandas as pd
import os

In [ ]:
house_data = pd.read_csv("data/merged_original_data.csv")
house_data.shape
genes_list = list(house_data['Gene'])

processed_data = pd.read_csv("data/ready2analyzed.csv")
processed_data.shape

processed_genes = processed_data.columns.tolist()
processed_genes

processed_genes.remove('Outcomes')

processed_genes

to_remove = []
for i in range(len(processed_genes)):
    if processed_genes[i] in genes_list:
        #print("gene existsed: ", processed_genes[i])
        pass
    else:
        print("gene not existed: ", processed_genes[i])
        to_remove.append(processed_genes[i])
        
processed_data.head(5)