In [1]:
import os
import shutil
import pandas as pd
import re

In [2]:
dfs = []
for file_name in os.listdir('data/finalized'):
    file_path = os.path.join("data/finalized", file_name)
    dfs.append(pd.read_csv(file_path))

In [3]:
result_df = dfs[3]
result_df.head(5)

,col,md0,md1,md2,md3,md4,md5,md6,md7,md8,md9,md10,md11
0,Outcomes,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000
1,TSPAN6,84.865100,76.867400,83.67390,59.774000,63.825400,61.571200,74.74600,84.07390,84.91110,77.98930,74.67730,66.80190
2,TNMD,0.395107,0.610888,1.35942,0.787316,0.218991,0.482109,2.98019,3.85128,4.19281,1.81964,1.48654,1.87628
3,DPM1,45.236200,41.082500,40.71090,48.908700,48.253600,46.886100,42.12880,42.51110,44.16380,38.34620,41.92180,40.12510
4,SCYL3,5.072610,3.924850,5.00336,6.014880,4.950510,5.380790,4.86405,4.61122,6.35072,5.93592,6.06586,3.68730

In [4]:
dfs.pop(-1)

,col,md0,md1,md2,md3,md4,md5,md6,md7,md8,md9,md10,md11
0,Outcomes,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.00000
1,TSPAN6,84.865100,76.867400,83.673900,59.774000,63.825400,61.571200,74.746000,84.073900,84.911100,77.989300,74.67730,66.80190
2,TNMD,0.395107,0.610888,1.359420,0.787316,0.218991,0.482109,2.980190,3.851280,4.192810,1.819640,1.48654,1.87628
3,DPM1,45.236200,41.082500,40.710900,48.908700,48.253600,46.886100,42.128800,42.511100,44.163800,38.346200,41.92180,40.12510
4,SCYL3,5.072610,3.924850,5.003360,6.014880,4.950510,5.380790,4.864050,4.611220,6.350720,5.935920,6.06586,3.68730
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57780,PGAM1,73.615000,79.976500,78.118400,77.236633,77.236633,77.236633,1.206935,1.270048,1.364314,69.549700,74.37870,73.05690
57781,FBP1,1.970380,1.847190,2.239970,1.386570,1.022450,1.324360,1.466770,2.440730,1.494780,1.805030,1.42438,2.03043
57782,PCK1,0.886300,0.655173,0.745203,6.689000,6.879940,7.011480,2.044120,1.619230,2.241540,5.839000,5.74252,5.61878
57783,FBP2,1.393150,1.248330,1.455760,1.104290,1.174290,1.025860,1.214780,1.381460,1.438400,1.605960,1.53108,1.49403
57784,PGAM2,0.000447,0.381709,0.638181,0.073682,0.000000,0.529615,2.458060,1.298460,1.011510,0.683592,2.01403,2.80613

In [5]:
len(dfs)

3

In [6]:
for df in dfs:
    result_df = pd.merge(result_df, df, on='col', how='left')

In [7]:
result_df.head(5)

,col,md0,md1,md2,md3,md4,md5,md6,md7,md8,...,vnd_0,vnd_1,vnd_2,vnd_3,cm1,cm2,cm3,cm4,cm5,cm6
0,Outcomes,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.00000,1.00000,1.00000,...,0.000000,0.0,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
1,TSPAN6,84.865100,76.867400,83.67390,59.774000,63.825400,61.571200,74.74600,84.07390,84.91110,...,486.872564,459.0,433.958026,460.543810,106.064417,111.616274,96.300058,127.592236,136.291185,134.182931
2,TNMD,0.395107,0.610888,1.35942,0.787316,0.218991,0.482109,2.98019,3.85128,4.19281,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.126213,0.000000,0.000000
3,DPM1,45.236200,41.082500,40.71090,48.908700,48.253600,46.886100,42.12880,42.51110,44.16380,...,980.686284,919.0,931.644154,821.696755,138.494512,136.715657,135.800300,125.367373,140.914166,142.903518
4,SCYL3,5.072610,3.924850,5.00336,6.014880,4.950510,5.380790,4.86405,4.61122,6.35072,...,122.957633,172.0,130.490875,128.912904,16.833704,16.350822,17.063865,16.721556,16.571374,16.719957

In [8]:
result_df.to_csv("data/finalized/combined_all.csv", index=False)

                          col   values
0                     Outcome        1
1                        A1BG       20
2                    A1BG-AS1       88
3                        A1CF        0
4                         A2M       31
...                       ...      ...
27457            __no_feature  3765480
27458             __ambiguous   265224
27459         __too_low_aQual        0
27460           __not_aligned        0
27461  __alignment_not_unique  7541225

[27462 rows x 2 columns]