In [1]:
import pandas as pd

In [2]:
mrg_data = pd.read_csv("merged.csv", header=None, index_col=False).T

C:\Users\MSI\AppData\Local\Temp\ipykernel_5432\2165047264.py:1: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135) have mixed types. Specify dtype option on import or set low_memory=False.
  mrg_data = pd.read_csv("merged.csv", header=None, index_col=False).T

In [3]:
print("mrg_data.shape: ", mrg_data.shape)
mrg_data.head(5)

mrg_data.shape:  (136, 20813)

,0,1,2,3,4,5,6,7,8,9,...,20803,20804,20805,20806,20807,20808,20809,20810,20811,20812
0,Gene,SEC24B-AS1,A1BG,A1CF,GGACT,A2M,A2ML1,A2MP1,A4GALT,A4GNT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2211090011-PBMC,2,2,0,5,13,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2211160007-PBMC,7,1,0,4,1,0,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2210050025-PBMC,14,78,68,0,2185,0,1,76,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2211150016-PBMC,1,3,0,3,1,0,2,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df = mrg_data
#set column names equal to values in row index position 0
df.columns = df.iloc[0]
#remove first row from DataFrame
df = df[1:]
print("df.shape: ", df.shape)
df.head(5)

df.shape:  (135, 20813)

,Gene,SEC24B-AS1,A1BG,A1CF,GGACT,A2M,A2ML1,A2MP1,A4GALT,A4GNT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2211090011-PBMC,2,2,0,5,13,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2211160007-PBMC,7,1,0,4,1,0,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2210050025-PBMC,14,78,68,0,2185,0,1,76,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2211150016-PBMC,1,3,0,3,1,0,2,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2211150008-PBMC,2,3,0,0,3,0,0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
nan_count = df.isna().sum()
threshold = 2
columns_to_drop = nan_count[nan_count > threshold].index
df_new = df.drop(columns=columns_to_drop)

In [6]:
nan_count = df_new.isna().sum()

In [7]:
df_new.shape

(135, 20785)

In [8]:
df_new2 = df_new.dropna()

In [9]:
nan_count = df_new2.isna().sum()

In [13]:
df_new3 = df_new2.drop(["Gene"], axis=1)

In [14]:
df_new3.head(5)

,SEC24B-AS1,A1BG,A1CF,GGACT,A2M,A2ML1,A2MP1,A4GALT,A4GNT,AAAS,...,ERCC-00031,ERCC-00042,ERCC-00069,ERCC-00084,ERCC-00097,ERCC-00112,ERCC-00131,ERCC-00136,ERCC-00157,ERCC-00171
1,2,2,0,5,13,0,0,0,0,61,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7,1,0,4,1,0,1,0,0,65,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,14,78,68,0,2185,0,1,76,0,447,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,3,0,3,1,0,2,0,0,49,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2,3,0,0,3,0,0,1,1,69,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
df_new3.to_csv("processed_data/merged_formatted.csv", index=False)

In [16]:
selected_features = ['ZFP36L2', 'CX3CR1', 'SLC12A7', 'GIMAP4', 'A2M', 'FMN1', 'IQGAP1', 'MTRNR2L10']
new_mrg_data = df_new3[selected_features]

In [17]:
new_mrg_data.to_csv("new_mrg_data.csv", index=False)